<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Hadil\Customers\Block\Customer\Form $block */

?>

<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData"  data-mage-init='{"validation": {}}' class="form"
              action="<?php echo $block->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill Detail')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                    escapeHtmlAttr(__('Name')) ?></span></label>
                            <div class="control">
                                <input name="customer_name" id="customer_name" title="Name" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>

                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                    escapeHtmlAttr(__('Contact Request')) ?></span></label>
                            <div class="control">
                                <input name="contact_request" id="contact_request" title="Contact Request" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>



                        <div class="field name required">
                            <label class="label" for="contact_reason">
                                <span><?= $block->escapeHtmlAttr(__('Contact reasons')) ?></span>
                            </label>
                            <div class="control">
                                <select name="contact_reason" id="contact_reason" class="select">
                                    <?php $options = $block->getContactOptions();
                                    foreach ($options as $element)
                                    {?>
                                        <option value="<?=$element['value']?>"><?=$element['label']?></option>
                                    <?php }?>

                                </select>
                            </div>
                        </div>

                     <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                    escapeHtmlAttr(__('Email')) ?></span></label>
                            <div class="control">
                                <input name="customer_email" id="customer_email" title="Email" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>


                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('Telephone')) ?></span></label>
                            <div class="control">
                                <input name="customer_phonenumber" id="customer_phonenumber" title="Telephone" value="" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
<!--                <div class="primary">-->
<!--                    <button type="submit" class="action submit primary" title="Save"><span>--><?php //= $block->
//                            escapeHtmlAttr(__('Save')) ?><!--</span></button>-->
<!--                </div>-->

                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save" >
                        <span><?= $block->escapeHtmlAttr(__('submit')) ?></span>
                    </button>
                </div>

            </div>


        </form>
    </div>
</div>

